const express = require('express')
const cors = require('cors')
const dotenv = require('dotenv').config()
const ejs = require('ejs')
const sequelize = require('sequelize')
const con = require('./app/config/db.js')
var mysql2 = require('mysql2')
const userRoutes = require('./app/routes/userRoutes.js')
const servicesRoutes = require('./app/routes/servicesRoutes.js')
const authRoutes = require('./app/routes/auth.js')
const model = require('./app/models/usersModel.js')
const app = express()
app.use(cors());
app.use(express.json({limit:'30mb', extended:true}))
app.use(express.urlencoded({limit:'30mb', extended:true}))
app.use(express.static('public'))
app.use(userRoutes)
app.use('/auth', authRoutes)
app.use(servicesRoutes)
app.set('view engine', 'ejs');
app.get('/', (req,res) => res.render('index'))
app.get('/protez-tirnak', (req,res) => res.render('protez-tirnak'))
app.get('/makyaj', (req,res) => res.render('normal-makyaj'))
app.get('/kalici-makyaj', (req,res) => res.render('kalici-makyaj'))
app.get('/cilt-bakim', (req,res) => res.render('cilt-bakim'))
app.get('/vip-cilt-bakim', (req,res) => res.render('vip-cilt-bakim'))
app.get('/agda', (req,res) => res.render('agda'))
app.get('/manikur-pedikur', (req,res) => res.render('manikur-pedikur'))
app.get('/lazer-epilasyon', (req,res) => res.render('lazer-epilasyon'))
app.get('/bolgesel-zayiflama', (req,res) => res.render('bolgesel-zayiflama'))
app.get('/hakkimizda', (req,res) => res.render('hakkimizda'))
app.get('/login', (req,res) => res.render('login'))
app.get('/admin', (req,res) => res.render('admin'))
const port = process.env.port || 3000;
app.listen(port, () => console.log('server ayakta') )